### ISSUE TITLE
Update "heater" fails

### ISSUE THREAD

**Issue by UdoK** [Danielhiversen/home_assistant_adax#27]
With the new version 0.4 I got new error messages now

Logger: homeassistant.helpers.entity
Source: custom_components/adax/adax.py:158
First occurred: 11:19:28 (13 occurrences)
Last logged: 15:32:26

Update for climate.essen fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 829, in _resolve_host
    addrs = await \
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 482, in async_device_update
    await task
  File "/config/custom_components/adax/climate.py", line 153, in async_update
    for room in await self._adax_data_handler.get_rooms():
  File "/config/custom_components/adax/adax.py", line 35, in get_rooms
    await self.update()
  File "/config/custom_components/adax/adax.py", line 48, in update
    await self.fetch_rooms_info()
  File "/config/custom_components/adax/adax.py", line 102, in fetch_rooms_info
    response = await self._request(API_URL + "/rest/v1/content/")
  File "/config/custom_components/adax/adax.py", line 144, in _request
    return await self._request(url, json_data, retry=retry - 1)
  File "/config/custom_components/adax/adax.py", line 116, in _request
    self._access_token = await get_adax_token(
  File "/config/custom_components/adax/adax.py", line 158, in get_adax_token
    response = await websession.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api-1.adax.no:443 ssl:default [Try again]

**Comment by Danielhiversen** [comment]
Do you get the same error with version 0.3?

**Comment by UdoK** [comment]
No, never have seen this error before in earlier versions

**Comment by Danielhiversen** [comment]
Have you tried to change back to 0.3 now?

**Comment by UdoK** [comment]
I downgraded to 0.3.0 and don't get the Update error but still Too May Requests when I want to control one of the heaters

Logger: custom_components.adax.climate
Source: custom_components/adax/climate.py:260
Integration: Adax (documentation, issues)
First occurred: 20:00:18 (22 occurrences)
Last logged: 22:38:40

Error connecting to Adax, response: 429 Too Many Requests

**Comment by Danielhiversen** [comment]
And it always happens at 0.4?

**Comment by UdoK** [comment]
After updating from 0.3 to 0.4 I'm getting no more errors, no Update errors an no Too May Requests 
Worked fine for the whole day

**Comment by Danielhiversen** [comment]
Then I assume it was some server issues at Adax. 
I have also added some retry functionality: https://github.com/Danielhiversen/home_assistant_adax/pull/29
