### ISSUE TITLE
Not getting any data at all from this adax integration

### ISSUE THREAD

**Issue by donagrejja** [Danielhiversen/home_assistant_adax#3]
Using Home Assistant version 0.114.4

Configuration.yaml:
climate:
  - platform: adax
    account_id: "xxxx"
    password: "xxxx"

Log:

Logger: homeassistant.components.climate
Source: custom_components/adax/climate.py:235
Integration: Climate (documentation, issues)
First occurred: 11:57:29 AM (1 occurrences)
Last logged: 11:57:29 AM

Error while setting up adax platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 184, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/adax/climate.py", line 43, in async_setup_platform
    for heater_data in await adax_data_handler.get_rooms():
  File "/config/custom_components/adax/climate.py", line 181, in get_rooms
    await self.update()
  File "/config/custom_components/adax/climate.py", line 193, in update
    await self.fetch_rooms_info()
  File "/config/custom_components/adax/climate.py", line 210, in fetch_rooms_info
    response = await self._request(API_URL + "/rest/v1/content/")
  File "/config/custom_components/adax/climate.py", line 235, in _request
    token_data = json.loads(await response.text())
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by donagrejja** [comment]
Maybe it's a name decoding issue of my rooms ? I'm using "()" in 2 of the room names.

**Comment by donagrejja** [comment]
Tried removing any non alphanumeric chars from my heater and room names and restarted homeassistant and it still didn't work. same error.

**Comment by donagrejja** [comment]
Nevermind. Just me fucking up accountid.
