### ISSUE TITLE
Failing to get token from Adax

### ISSUE THREAD

**Issue by badguy99** [Danielhiversen/home_assistant_adax#32]
integration is failing to come up after a restart of Home Assistant, and also after a reload of the component. It fails to get a token from Adax, with a traceback 

```
2020-11-19 00:21:58 ERROR (MainThread) [custom_components.adax.adax] Error getting token Adax: Cannot connect to host api-1.adax.no:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 829, in _resolve_host
    addrs = await \
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/adax/adax.py", line 160, in get_adax_token
    response = await websession.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api-1.adax.no:443 ssl:default [Try again]
2020-11-19 00:21:58 INFO (MainThread) [custom_components.adax.config_flow] Adax: Failed to login to retrieve token
```

If I try using the example code here https://adax.no/en/about-adax/api-development/ with the same account and secret details, I get a token and can get the home info.

**Comment by Danielhiversen** [comment]
Do you use the latest version of the component?

**Comment by badguy99** [comment]
I tried 0.4.1 and 0.4.2 and had the same issue on both. However this morning it is working correctly. I'm not sure what happened, maybe some rate limiting / fail2ban type thing on their side, though I'm not sure why I could get it to work in ipython on a different rPi with their example code, but not from HA, last night, as both requests would have been from the same external IP. Anyway, this looks good to me now, so I will close it.

**Comment by acseven** [comment]
I'm also seeing some errors in my log:

`Logger: custom_components.adax.adax
Source: custom_components/adax/adax.py:83
Integration: Adax (documentation, issues)
First occurred: 1:00:00 (6 occurrences)
Last logged: 7:31:01

Too many requests, will retry`

Component is updated (0.4.2)
