### ISSUE TITLE
JSON parsing error

### ISSUE THREAD

**Issue by vibrog** [Danielhiversen/home_assistant_adax#5]
2020-09-18 07:54:40 ERROR (MainThread) [homeassistant.components.climate] Error while setting up adax platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/adax/climate.py", line 43, in async_setup_platform
    for heater_data in await adax_data_handler.get_rooms():
  File "/config/custom_components/adax/climate.py", line 177, in get_rooms
    await self.update()
  File "/config/custom_components/adax/climate.py", line 189, in update
    await self.fetch_rooms_info()
  File "/config/custom_components/adax/climate.py", line 206, in fetch_rooms_info
    response = await self._request(API_URL + "/rest/v1/content/")
  File "/config/custom_components/adax/climate.py", line 231, in _request
    token_data = json.loads(await response.text())
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Danielhiversen** [comment]
Are you sure the login credentials are correct?

`account_id` is a number you find in the app
`password` is **not** your login password, but the password generated in the adax app

**Comment by aaresa** [comment]
Hi,

I got the same problem

```
2020-09-18 15:20:21 ERROR (MainThread) [homeassistant.components.climate] Error while setting up adax platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/adax/climate.py", line 43, in async_setup_platform
    for heater_data in await adax_data_handler.get_rooms():
  File "/config/custom_components/adax/climate.py", line 181, in get_rooms
    await self.update()
  File "/config/custom_components/adax/climate.py", line 193, in update
    await self.fetch_rooms_info()
  File "/config/custom_components/adax/climate.py", line 210, in fetch_rooms_info
    response = await self._request(API_URL + "/rest/v1/content/")
  File "/config/custom_components/adax/climate.py", line 235, in _request
    token_data = json.loads(await response.text())
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I added new credentials through the app and pasted them in the configuration.yaml file. Oddly enough I get the same error if the type a wrong account_id or password

**Comment by vibrog** [comment]
> Are you sure the login credentials are correct?
> 
> `account_id` is a number you find in the app
> `password` is **not** your login password, but the password generated in the adax app

Quite sure both are correct. Also triple checked them for typos.

**Comment by Danielhiversen** [comment]
Version 0.2.3 has better logging for this
